# Generated by Django 5.0.4 on 2024-04-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('balance_after_borrow', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.useraccount')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
