# Generated by Django 5.0.4 on 2024-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='History_type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Borrow', 'Borrow'), ('Return', 'Return')], max_length=10, null=True),
        ),
    ]
