# Generated by Django 5.0.4 on 2024-04-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author'),
        ('history', '0003_history_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.book'),
        ),
    ]
