# Generated by Django 5.0.4 on 2024-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_rename_history_type_history_history_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
